import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          CustTampilanAwal(),
        ]),
      ),
    );
  }
}

class CustTampilanAwal extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF010101),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 428,
                  padding: const EdgeInsets.only(
                    top: 21,
                    left: 24,
                    right: 24,
                    bottom: 19,
                  ),
                  decoration: BoxDecoration(color: Colors.black),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 154,
                    children: [
                      Expanded(
                        child: Container(
                          height: 22,
                          padding: const EdgeInsets.only(top: 1.50),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Text(
                                '9:41',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: const Color(0xFFD1D1D6) /* Grays-Gray-4 */,
                                  fontSize: 17,
                                  fontFamily: 'SF Pro',
                                  fontWeight: FontWeight.w590,
                                  height: 1.29,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Expanded(
                        child: Container(
                          height: 22,
                          padding: const EdgeInsets.only(top: 1, right: 1),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 7,
                            children: [
                              Container(
                                width: 27.33,
                                height: 13,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Opacity(
                                        opacity: 0.35,
                                        child: Container(
                                          width: 25,
                                          height: 13,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1,
                                                color: const Color(0xFFD1D1D6) /* Grays-Gray-4 */,
                                              ),
                                              borderRadius: BorderRadius.circular(4.30),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 2,
                                      top: 2,
                                      child: Container(
                                        width: 21,
                                        height: 9,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFFD1D1D6) /* Grays-Gray-4 */,
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(2.50),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -208,
                top: 362,
                child: Container(
                  width: 783,
                  height: 599,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/783x599"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 95,
                top: 122,
                child: Text(
                  'SELAMAT \n\n DATANG',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 48,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w900,
                    height: 0.46,
                  ),
                ),
              ),
              Positioned(
                left: 113,
                top: 219,
                child: Text(
                  'DI',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 40,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 0.55,
                  ),
                ),
              ),
              Positioned(
                left: 165,
                top: 219,
                child: SizedBox(
                  width: 157,
                  child: Text(
                    'K-16',
                    style: TextStyle(
                      color: const Color(0xFFFED917),
                      fontSize: 64,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 0.34,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 298,
                child: SizedBox(
                  width: 217,
                  height: 55.22,
                  child: Text(
                    'LANJUTKAN',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 32,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w900,
                      height: 0.69,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 305,
                top: 310,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  height: 33,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}